baseurl = "https://example.com/"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = ""
  themeColor = "orange"
  showMenuItems = 5
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Tarik Kelestemur"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Tarik Kelestemur"
      logoHomeLink = "/"
    [languages.en.menu]
    [[languages.en.menu.main]]
        identifier = "about"
        name = "About Me"
        url = "/"
      [[languages.en.menu.main]]
        identifier = "pubs"
        name = "Publications"
        url = "/publications"
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/tkelestemur"
      [[languages.en.menu.main]]
        identifier = "twitter"
        name = "Twitter"
        url = "https://twitter.com/tarikkelestemur"
      [[languages.en.menu.main]]
            identifier = "podcast"
            name = "Podcast [TR]"
            url = "https://open.spotify.com/show/6xh1JvolfduK8j5sb1WnoC"